chat:
  enabled: true

tab:
  enabled: true

colors:
  overworld:  "#00FF00" # or GREEN / green
  nether:     "#FF0000" # or RED / red
  end:        "#FF55FF" # or LIGHT_PURPLE / light_purple
  default:    "#FFFFFF" # or WHITE / white

  # Custom world example:
  # custom_world_name: "#RRGGBB" or standard color name
