name: DimensionTracker
version: '${version}'
main: ru.prokdo.DimensionTracker
api-version: '26.2'

softdepend: [PlaceholderAPI]

softdepend: [PlaceholderAPI]

permissions:
  dimensiontracker.reload:
    description: Allow reloading DimensionTracker config
    default: op
  dimensiontracker.afk:
    description: Allows toggling AFK status manually
    default: true