name: DimensionTracker
version: '${project.version}'
main: ru.prokdo.DimensionTracker
api-version: '1.21'

permissions:
  dimensiontracker.reload:
    description: Allow reloading DimensionTracker config
    default: op
  dimensiontracker.afk:
    description: Allows toggling AFK status manually
    default: true